name: 'Changelog Parser'
description: 'Parses changelog file'
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  path:
    description: 'Path to the changelog file. By default standard changelog locations are used.'
    required: false
    default: ''
  version:
    description: 'Version of the changelog entry. By default the last released version is used.'
    required: false
    default: ''
outputs:
  version:
    description: 'Version from the changelog entry'
  versionMajor:
    description: 'The major version part'
  versionMinor:
    description: 'The minor version part'
  versionPatch:
    description: 'The patch version part'
  buildNumber:
    description: 'Build number (only for non-prod versions)'
  suffix:
    description: 'Suffix for non-prod versions (dev, rc, int)'
  date:
    description: 'Release date from the changelog entry'
  description:
    description: 'Description from the changelog entry'
  isProductionRelease:
    description: 'true if version is a production release (e.g. v1.2.3), false otherwise'
runs:
  using: 'node20'
  main: 'build/dist/index.js'
